project:
  type: website

website:
  title: "Resource Competition Seminar"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/xl0418/
      - icon: linkedin
        href: https://www.linkedin.com/in/liangxuhuang
        
format:
  html:
    theme: yeti
    css: styles.css
    page-layout: full

editor: visual

# Enable the shinylive filter globally
filters:
  - shinylive

