---
title: "04 -- The resource-consumer competition model"
author: "Christopher Klausmeier; Liang Xu"
date: "2024-02-15"
categories: [Lectures]
filters:
  - shinylive
---

```{r setup, include=FALSE}
library(plotly)
library(magrittr)
```

Paper discussion: The three-species problem: incorporating competitive asymmetry and intransitivity in modern coexistence theory by **Ravi Ranjan**, **Thomas Koffel**, **Christopher A. Klausmeier**. (Link to the paper will be added soon)

We talked about the three species competition. There are many types of competition outcomes. They are determined by the 12 parameters in the model, i.e., the three intrinsic growth rates and 9 pairwise competition coefficients. The authors showed that the outcome of the competition is associated with the cyclic asymmetry, which is a triplet-wise quantity.

> # Paper Abstract
>
> While natural communities can contain hundreds of species, modern coexistence theory focuses primarily on species pairs. Alternatively, the structural stability approach considers the feasibility of equilibria, gaining scalability to larger communities but sacrificing information about dynamic stability. Three-species competitive communities are a bridge to more-diverse communities. They display novel phenomena while remaining amenable to mathematical analysis, but remain incompletely understood. Here, we combine these approaches to identify the key quantities that determine the outcome of competition. We show that pairwise niche overlap and fitness differences are insufficient to completely characterize competitive outcomes, which requires a strictly triplet-wise quantity: cyclic asymmetry. Low pairwise niche overlap stabilizes the triplet, while high fitness differences promote competitive exclusion. The effect of cyclic asymmetry on stability is complex and depends on pairwise niche overlap. In summary, we elucidate how pairwise niche overlap, fitness differences, and cyclic asymmetry determine the outcome of three-species competition.

# Model

The two-species resource-consumer competition model is defined as

$$
\begin{aligned}
\frac{dN_1}{dt} &=  \left(\mu_1 - m \right) N_1 \\
\frac{dN_2}{dt} &=  \left(\mu_2 - m \right) N_2 \\
\frac{dR}{dt} &=  a \left(R_{in}-R \right) - V_1 N_1 - V_2 N_2
\end{aligned}
$$

where $N_1$, $N_2$ and $N_3$ are the population sizes of species 1, 2 and 3, respectively, $r_1$, $r_2$ and $r_3$ are the intrinsic growth rates, and $\alpha_{ij}$s are the competition coefficients.


# The simulation

```{shinylive-r}
#| standalone: true
#| viewerHeight: 700
#| viewerWidth: 1000

library(shiny)
library(bslib)
library(plotly)
library(Matrix)

Sim_rc <- function(tt, mu11, mu12, mu21, mu22, v11, v12, v21, v22, m, a, r1in, r2in, N10, N20, R10, R20,
                   mode = "essential") {
  N1 <- c(N10)
  N2 <- c(N20)
  R1 <- c(R10)
  R2 <- c(R20)
  for(ti in 1:tt){
    if(mode == "essential"){
      mu1 <- min(mu11 * R1[ti], mu12 * R2[ti])
      mu2 <- min(mu21 * R1[ti], mu22 * R2[ti])
    } else {
      mu1 <- mu11 * R1[ti] + mu21 * R2[ti]
      mu2 <- mu12 * R1[ti] + mu22 * R2[ti]
    }

    dN1 <- (mu1  - m) * N1[ti]
    dN2 <- (mu2  - m) * N2[ti]
    N1 <- c(N1, N1[ti] + dN1)
    N2 <- c(N2, N2[ti] + dN2)
    
    dR1 <- a * (r1in - R1[ti]) - v11 * N1[ti] - v12 * N2[ti]
    dR2 <- a * (r2in - R2[ti]) - v21 * N1[ti] - v22 * N2[ti]
    R1 <- c(R1, R1[ti] + dR1)
    R2 <- c(R2, R2[ti] + dR2)
  }
  return(data.frame(N1 = N1, N2 = N2, R1 = R1, R2 = R2, cc = 1:(tt+1)))
  
}


# Define UI for app that draws a histogram ----
# Define UI for app that draws a histogram ----
ui <- fluidPage(
  headerPanel(''),
  
  fluidRow(
    column(12, 
           textOutput("text"),
           tags$head(tags$style("#text{color: black;
                                 font-size: 30px;
                                 font-style: italic;
                                 }"
           )
           ),
           plotlyOutput("plot", width=860)
    )
  ), 
  
  fluidRow(
    column(4, 
           div(style="height: 80px;",sliderInput('r1', 'r1', 0.4, min = 0.1, max = 3)),
           div(style="height: 80px;",sliderInput('r2', 'r2', 1.1, min = 0.1, max = 3))
    ),
    column(4,
           div(style="height: 80px;", sliderInput('alpha11', HTML("&alpha;<sub>11</sub>"), 1.5, min = 0.1, max = 5)),
           div(style="height: 80px;",sliderInput('alpha12', HTML("&alpha;<sub>12</sub>"), 0.8, min = 0.1, max = 5))
    ),
    column(4,
           div(style="height: 80px;",sliderInput('alpha21', HTML("&alpha;<sub>21</sub>"), 0.9, min = 0.1, max = 5)),
           div(style="height: 80px;",sliderInput('alpha22', HTML("&alpha;<sub>22</sub>"), 1.1, min = 0.1, max = 5))
    )
  )
  
  
)

server <- function(input, output, session) {
  N1 <- seq(0, 20, 0.01)
  N2_1 <-reactive({
    (input$r1 - input$alpha11 * N1) / input$alpha12 
  })
  
  N2_2 <- reactive({
    (input$r2 - input$alpha21 * N1) / input$alpha22
  })

  
  # sim lv model
  sim_result <- reactive({
    Sim_lotka_volterra(100, input$alpha11, input$alpha12, input$alpha21, input$alpha22, input$r1, input$r2, 0.1, 0.1)
  })
  
  output$text <- renderText({
    if(input$r1 / input$alpha11 > input$r2 / input$alpha21 & input$r1 / input$alpha12 >  input$r2 / input$alpha22){HTML("Case 1: Species 1 wins")}
    else if(input$r1 / input$alpha11 < input$r2 / input$alpha21 & input$r1 / input$alpha12 <  input$r2 / input$alpha22){"Case 2: Species 2 wins"}
    else if(input$r1 / input$alpha11 < input$r2 / input$alpha21 & input$r1 / input$alpha12 >  input$r2 / input$alpha22){"Case 3: Coexistence"}
    else if(input$r1 / input$alpha11 > input$r2 / input$alpha21 & input$r1 / input$alpha12 <  input$r2 / input$alpha22){"Case 4: Founder control"}
    else {"Case 5: Neutrality"}
    
  })
  
  output$plot <- renderPlotly({
    Ns <- data.frame(N1 = N1, N2_1 = N2_1(), N2_2 = N2_2())
    pos_Ns <- Ns[Ns$N2_1 >= 0 | Ns$N2_2 >= 0,]
    x_lim <- c(0, max(pos_Ns$N1) + 1)
    y_lim <- c(0, max(pos_Ns$N2_1, pos_Ns$N2_2)+1)
    p <- plot_ly(x = N1, y = N2_1(), type = 'scatter', mode = 'lines', name = 'dN1/dt = 0') %>%
      add_trace(x = N1, y = N2_2(), type = 'scatter', mode = 'lines', name = 'dN2/dt = 0') %>%
      add_trace(x = -1, y = -1, type = 'scatter', mode = 'markers', name = 'Stable equilibrium point',
                marker = list(color = 'rgb(0, 0, 0)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                             width = 1
                ))) %>%
      add_trace(x = -2, y = -1, type = 'scatter', mode = 'markers', name = 'Unstable equilibrium point',
                marker = list(color = 'rgb(255, 255, 255)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                             width = 1
                ))) %>%
      add_trace(x = sim_result()$N1, y = sim_result()$N2, type = 'scatter', mode = 'lines+markers', name = 'Trajectory', 
                marker = list(color = 'grey'), line = list(color = 'grey')) %>%
      add_trace(x = 0.1, y=0.1, type = 'scatter', mode = 'markers', name = 'Initial condition',
                marker = list(color = 'rgb(0, 0, 0)', size = 5, line = list(color = 'rgb(0, 0, 0)',
                                                                             width = 1
                )))
    
    if(input$r1 / input$alpha11 > input$r2 / input$alpha21 & input$r1 / input$alpha12 >  input$r2 / input$alpha22){
      p <- p %>%
        add_trace(x = input$r1 / input$alpha11, y = 0, type = 'scatter', mode = 'markers', name = 'Stable equilibrium point',
                  marker = list(color = 'rgb(0, 0, 0)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                               width = 1
                  )), showlegend = FALSE) %>%
        add_trace(x = 0, y = input$r2 / input$alpha22, type = 'scatter', mode = 'markers', name = 'Unstable equilibrium point',
                  marker = list(color = 'rgb(255, 255, 255)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                               width = 1
                  )), showlegend = FALSE) %>%
        add_trace(x = 0, y = 0, type = 'scatter', mode = 'markers', name = 'Unstable equilibrium point',
                  marker = list(color = 'rgb(255, 255, 255)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                                     width = 1
                  )), showlegend = FALSE) %>%
        layout(xaxis = list(title = 'N1', range = x_lim), yaxis = list(title = 'N2', range = y_lim))
    } else if(input$r1 / input$alpha11 < input$r2 / input$alpha21 & input$r1 / input$alpha12 <  input$r2 / input$alpha22){

        p <- p %>%
          add_trace(x = input$r1 / input$alpha11, y = 0, type = 'scatter', mode = 'markers', name = '',
                  marker = list(color = 'rgb(255, 255, 255)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                               width = 1
                  )), showlegend = FALSE) %>%
        add_trace(x = 0, y = input$r2 / input$alpha22, type = 'scatter', mode = 'markers', name = '',
                  marker = list(color = 'rgb(0, 0, 0)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                               width = 1
                  )), showlegend = FALSE) %>%
        add_trace(x = 0, y = 0, type = 'scatter', mode = 'markers', name = '',
                  marker = list(color = 'rgb(255, 255, 255)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                                     width = 1
                  )), showlegend = FALSE) %>%
        layout(xaxis = list(title = 'N1', range = x_lim), yaxis = list(title = 'N2', range = y_lim))
    } else if(input$r1 / input$alpha11 < input$r2 / input$alpha21 & input$r1 / input$alpha12 >  input$r2 / input$alpha22){
      sol <- reactive({solve(matrix(c(input$alpha11, input$alpha21, input$alpha12, input$alpha22), 2, 2), c(input$r1, input$r2))})
      
      p <- p %>%
        add_trace(x = sol()[1], y = sol()[2], type = 'scatter', mode = 'markers', name = '',
                       marker = list(color = 'rgb(0, 0, 0)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                                    width = 1
                       )), showlegend = FALSE) %>%
        add_trace(x = input$r1 / input$alpha11, y = 0, type = 'scatter', mode = 'markers', name = '',
                  marker = list(color = 'rgb(255, 255, 255)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                                     width = 1
                  )), showlegend = FALSE) %>%
        add_trace(x = 0, y = input$r2 / input$alpha22, type = 'scatter', mode = 'markers', name = '',
                  marker = list(color = 'rgb(255, 255, 255)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                               width = 1
                  )), showlegend = FALSE) %>%
        add_trace(x = 0, y = 0, type = 'scatter', mode = 'markers', name = '',
                  marker = list(color = 'rgb(255, 255, 255)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                                     width = 1
                  )), showlegend = FALSE) %>%
        layout(xaxis = list(title = 'N1', range = x_lim), yaxis = list(title = 'N2', range = y_lim))
      
    } else if(input$r1 / input$alpha11 > input$r2 / input$alpha21 & input$r1 / input$alpha12 <  input$r2 / input$alpha22){
      sol <- reactive({solve(matrix(c(input$alpha11, input$alpha21, input$alpha12, input$alpha22), 2, 2), c(input$r1, input$r2))})
      
      p <- p %>%
        add_trace(x = sol()[1], y = sol()[2], type = 'scatter', mode = 'markers', name = '',
                  marker = list(color = 'rgb(255, 255, 255)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                               width = 1
                  )), showlegend = FALSE) %>%
        add_trace(x = input$r1 / input$alpha11, y = 0, type = 'scatter', mode = 'markers', name = '',
                  marker = list(color = 'rgb(0, 0, 0)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                               width = 1
                  )), showlegend = FALSE) %>%
        add_trace(x = 0, y = input$r2 / input$alpha22, type = 'scatter', mode = 'markers', name = '',
                  marker = list(color = 'rgb(0, 0, 0)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                                     width = 1
                  )), showlegend = FALSE) %>%
        add_trace(x = 0, y = 0, type = 'scatter', mode = 'markers', name = '',
                  marker = list(color = 'rgb(255, 255, 255)', size = 10, line = list(color = 'rgb(0, 0, 0)',
                                                                                     width = 1
                  )), showlegend = FALSE) %>%
        layout(xaxis = list(title = 'N1', range = x_lim), yaxis = list(title = 'N2', range = y_lim))
    } else {
      p <- p %>%
        layout(xaxis = list(title = 'N1', range = x_lim), yaxis = list(title = 'N2', range = y_lim))
    }
    
    p
  })
  
}
# Create Shiny app ----
shinyApp(ui = ui, server = server)
```

# References

**Ravi Ranjan**, **Thomas Koffel**, **Christopher A. Klausmeier**, The three-species problem: incorporating competitive asymmetry and intransitivity in modern coexistence theory, 2024, in press.
